### ISSUE TITLE
Does not work with browserify

### ISSUE THREAD

**Issue by thetutlage** [davidchang/ngReact#37] opened 2015-01-04 06:45 UTC
No matter what it does not work with browserify

I have tried using angular and ngReact from npm and it failed.
Then i tried using http://ngcli.github.io/ , which auto converts bower_components to simple require() statements and it even failed there.

Error message

 undefined is not a function on below line.

```
  return angular.module('react', [])
```

require("angular") is available to my app so it should be available to ngReact , not sure what is the issue here.

**Comment by thetutlage** [comment] 2015-01-04 07:25
I have created a repo and it makes use of browserify https://github.com/thetutlage/ng-react-test

If u have time , clone and see what is the real deal

**Comment by kasperp** [comment] 2015-01-04 09:20
@thetutlage I think the problem is that the angular npm package doesn't export angular, so `require( 'angular' )` returns `undefinded`. 

> Note that this package is not in CommonJS format, so doing require('angular') will return undefined. If you're using Browserify, you can use exposify to have require('angular') return the angular global.
>
> -- <cite>https://www.npmjs.com/package/angular</cite>

We use browserify when we run the tests in this repository and ran into this issue as well. To solve it we run angular through [browserify shim](https://github.com/thlorenz/browserify-shim) see.  https://github.com/davidchang/ngReact/blob/master/karma.config.js#L19

I'm closing this, feel free to reopen if this isn't the problem you are seeing.

**Closed by kasperp** 2015-01-04 09:20 UTC

**Comment by thetutlage** [comment] 2015-01-04 10:45
I have also used bower and still it has same issue ..

**Comment by thetutlage** [comment] 2015-01-04 10:50
I have created a pull request and that simply works 
https://github.com/davidchang/ngReact/pull/38
